name: shelf_backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.0.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^3.0.0
  mocktail: ^1.0.0
  shelf_router_generator: ^1.1.0
  test: ^1.16.0
dependencies: { shelf: ^1.4.1, shelf_router: ^1.1.4}
